-- Event vocabulary (design §5.3). Applied by `framework init-db`; safe to re-run.
INSERT INTO ComplianceEventType (Event_Ty, Log_Tbl_Cd, Event_Ctgy, Default_Sevrty, Notify_Ind) VALUES
  -- batch timeline (ComplianceRequestFileDetail)
  ('BATCH_CREATED','FILE_DETAIL','AUDIT','INFO',0),
  ('BATCH_CLOSED','FILE_DETAIL','AUDIT','INFO',0),
  ('FILE_RECEIVED','FILE_DETAIL','AUDIT','INFO',0),
  ('FILE_REPLACED_BEFORE_CLOSE','FILE_DETAIL','AUDIT','INFO',0),
  ('FILE_PROMOTED','FILE_DETAIL','AUDIT','INFO',0),
  ('FILE_RULES_FAILED','FILE_DETAIL','EXCEPTION','ERROR',0),
  ('LATE_ARRIVAL_PROMOTED','FILE_DETAIL','AUDIT','INFO',0),
  ('CORRECTION_PROMOTED','FILE_DETAIL','AUDIT','INFO',0),
  ('CARRY_FORWARD_APPLIED','FILE_DETAIL','AUDIT','INFO',0),
  ('CARRY_FORWARD_REMOVED','FILE_DETAIL','AUDIT','INFO',0),
  -- intake
  ('INTAKE_FAILED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('INTAKE_COMPLETED','EXCEPTIONS_AUDIT','AUDIT','INFO',0),
  ('BATCH_CREATE_SKIPPED_EXTRACT_CLOSED','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',1),
  -- file intake
  ('FILE_REJECTED_UNPARSEABLE','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_AMBIGUOUS_TEMPLATE','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_INVALID_TOKEN','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_RUNTY_NOT_CONFIGURED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_NO_BATCH','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_BATCH_CLOSED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_REJECTED_DUPLICATE','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',1),
  ('FILE_EVENT_REPLAY_IGNORED','EXCEPTIONS_AUDIT','AUDIT','INFO',0),
  ('FILE_SAME_CONTENT_OTHER_BATCH','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',1),
  ('FILE_PARSE_ERROR','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_COLUMN_COUNT_MISMATCH','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_TRAILER_COUNT_MISMATCH','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_ZERO_RECORDS_REJECTED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_TYPE_NOT_SUPPORTED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('FILE_MOVE_FAILED','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',0),
  -- validation / load
  ('RULES_VALIDATION_FAILED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('RULES_ENGINE_TECHNICAL_FAILURE','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('CORE_LOAD_ROWCOUNT_MISMATCH','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('INVALID_STATUS_TRANSITION','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  -- manual decisions
  ('OVERRIDE_APPROVED','EXCEPTIONS_AUDIT','AUDIT','WARNING',1),
  ('OVERRIDE_REJECTED','EXCEPTIONS_AUDIT','AUDIT','INFO',0),
  ('OVERRIDE_INVALID_DETECTED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('OVERRIDE_EXPIRED','EXCEPTIONS_AUDIT','AUDIT','WARNING',1),
  -- extract
  ('PERIOD_RULES_FAILED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1),
  ('EXTRACT_ELIGIBILITY_CHANGED','EXCEPTIONS_AUDIT','AUDIT','INFO',0),
  ('EXTRACT_CLOSED','EXCEPTIONS_AUDIT','AUDIT','INFO',1),
  ('EXTRACT_CLOSED_WITH_WARNINGS','EXCEPTIONS_AUDIT','AUDIT','WARNING',1),
  ('EXTRACT_CLOSE_BLOCKED','EXCEPTIONS_AUDIT','AUDIT','WARNING',0),
  ('EXTRACT_CLOSE_DEFERRED_LOCKED','EXCEPTIONS_AUDIT','AUDIT','INFO',0),
  ('EXTRACT_REGENERATE_REQUIRED','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',1),
  ('SOURCE_MISSING_AT_CLOSE','EXCEPTIONS_AUDIT','EXCEPTION','WARNING',1),
  -- config
  ('CONFIG_VALIDATION_FAILED','EXCEPTIONS_AUDIT','EXCEPTION','ERROR',1)
ON CONFLICT (Event_Ty) DO UPDATE SET Log_Tbl_Cd=EXCLUDED.Log_Tbl_Cd, Event_Ctgy=EXCLUDED.Event_Ctgy,
  Default_Sevrty=EXCLUDED.Default_Sevrty;
